- name: Demo on vars
  hosts: local host
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
       msg: URL_PLAY - {{ URL_PLAY }}
    - name: Task Variable
      ansible.builtin.debug:
        msg: URL_TASK - {{ URL_TASK }}
      vars:
        URL_TASK: tasks.example.com

  roles:
    - demo
