- name: demo in template
  hosts: localhosts
  tasks:
    - name: example.conf
      ansible.builtin.conf:
        src: example.conf
        dest: /tmp/example-copy.conf


    - name: template example.conf
      ansible.builtin.template:
        src: example.conf
        dest: /tmp/example-template.conf
